openapi: 3.0.0
info:
  version: "1"
  title: "CatalogData"
  description: Get product info from catalog
servers:
  - url: http://catalog/openapi/CatalogData/v1
tags:
  - name: Catalog
paths:
  "/product/{marketplace}/{rid}":
    get:
      tags:
        - Catalog
      summary: "Get product info by rid for specific marketplace"
      parameters:
        - name: marketplace
          in: path
          required: true
          schema:
            type: string
            enum:
              - EbayPlaisir
              - EbayRollun
        - name: rid
          in: path
          required: true
          schema:
            type: string
        - name: include
          in: query
          required: false
          description: If set, only this fields will be returned. Format - field names separated by coma
          schema:
            type: string
        - name: exclude
          in: query
          required: false
          description: If set, this fields will NOT be returned. Format - field names separated by coma
          schema:
            type: string
      responses:
        "200":
          description: "Success"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProductResponse"
        "500":
          description: "Internal error"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        messages:
          type: array
          items:
            $ref: "#/components/schemas/Message"
      description: "Message field is not required"
    Message:
      type: object
      properties:
        level:
          type: string
          enum:
            - emergency
            - alert
            - critical
            - error
            - warning
            - notice
            - info
        type:
          type: string
          enum:
            - UNDEFINED
            - INVALID_RESPONSE
          description: >
            UNDEFINED - Any undefined message type
            INVALID_RESPONSE - A message generated by the client stating that the response could not be decoded
        text:
          type: string
          description: Message, that describes what went wrong
    SuccessResponse:
      allOf:
        - $ref: '#/components/schemas/ErrorResponse'
      type: object
      properties:
        data:
          type: object
    ProductResponse:
      type: object
      allOf:
        - $ref: '#/components/schemas/SuccessResponse'
      properties:
        data:
          $ref: '#/components/schemas/Product'

    ## Resource object
    Product:
      type: object
      required:
        - rid
      properties:
        rid:
          type: string
        quantity:
          type: integer
        price:
          type: number
        brand:
          type: string
        mpn:
          type: string
        title:
          type: string
        description:
          type: string
        photoUris:
          type: array
          items:
            type: string
        location:
          type: string
