openapi: 3.0.0
info:
  version: "1"
  title: "CRMData"
  description: Allows to retrieve data from CRM
servers:
  - url: http://rollun-crm/openapi/CRMData/v1
tags:
  - name: CRMData
paths:
  "/getRelatedEntities/{itemType}/{itemId}":
    get:
      tags:
        - CRMData
      description: "Get related entities for some item"
      parameters:
        - name: itemType
          in: path
          required: true
          schema:
            type: string
            enum:
              - deal
        - name: itemId
          in: path
          required: true
          schema:
            type: string
        - name: relationType
          description: "Filter to get only relations with this type"
          in: query
          required: false
          schema:
            type: string
            enum:
              - deal
        - name: programId
          description: "Filter to get only related deals with this programId"
          in: query
          required: false
          schema:
            type: string
      responses:
        "200":
          description: "Success response"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RelatedEntitiesResponse'
        "500":
          description: 'Some error'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  "/addRelation":
    post:
      tags:
        - CRMData
      description: "Add new relation"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Relation'
      responses:
        "200":
          description: "Success response"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RelationResponse'
        "500":
          description: 'Some error'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    ## General
    Message:
      type: object
      properties:
        level:
          type: string
          enum:
            - emergency
            - alert
            - critical
            - error
            - warning
            - notice
            - info
        text:
          type: string
          description: Message, that describes what went wrong
    ErrorResponse:
      type: object
      properties:
        messages:
          type: array
          items:
            $ref: "#/components/schemas/Message"
      description: "Message field is not required"
    SuccessResponse:
      allOf:
        - $ref: '#/components/schemas/ErrorResponse'
      type: object
      required:
        - data
      properties:
        data:
          type: object

    ## Custom responses
    RelatedEntitiesResponse:
      allOf:
        - $ref: '#/components/schemas/SuccessResponse'
      type: object
      required:
        - data
      properties:
        data:
          type: array
          items:
            $ref: "#/components/schemas/RelatedEntity"
    RelationResponse:
      allOf:
        - $ref: '#/components/schemas/SuccessResponse'
      type: object
      required:
        - data
      properties:
        data:
          type: object
          allOf:
            - $ref: '#/components/schemas/Relation'

    ## Resources
    RelatedEntity:
      type: object
      required:
        - relation
        - data
      properties:
        relation:
          type: object
          allOf:
            - $ref: '#/components/schemas/Relation'
        data:
          type: object
          additionalProperties: true

    Relation:
      type: object
      required:
        - dealId
        - entityType
        - entityId
      properties:
        dealId:
          type: string
        entityType:
          type: string
          enum:
            - deal
        entityId:
          type: string