openapi: 3.0.0
info:
  version: "1"
  title: "CRMDropships"
  description: >
    This is an API for Dropship deals managment
    

    *Question to discuss*
      - Deduplication logic in post methods?
      - Id of entities will be generated. What format? UUID? Incremental id with prefix?
      - additional tracknumbers field?
      - enter tracknumber field?
      - archive scenario field?
      - ret_bag?

servers:
  - url: http://server-host/openapi/CRMDropships/v1
tags:
  - name: DropshipDeals
paths:
  "/dropships":
    post:
      tags:
        - DropshipDeals
      summary: "Create An Dropship Deal"
      description: ""
      requestBody:
        description: ""
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DropshipDealPostRequest'
      responses:
        "200":
          description: "Dropship Deal successfully created"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DropshipDealResult'
        "500":
          description: 'Some internal error'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResult'
    get:
      tags:
        - DropshipDeals
      summary: "Get list of Dropship Deals"
      description: "Get list of Dropship Deals"
      parameters:
        - in: query
          name: "filter"
          example: "eq(mpDropshipNumber,string:01-01-01)"
          description: "Returning Dropships with by a specific rql filter."
          required: false
          schema:
            type: string
      responses:
        "200":
          description: "Success"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DropshipDealListResult"
        '500':
          description: "Internal error"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResult'
  "/dropships/{id}":
    get:
      tags:
        - DropshipDeals
      summary: 'Get info about specific Dropship Deal'
      description: "Returns information of Dropship Deal by id"
      parameters:
        - in: path
          name: id
          description: Id of resource
          required: true
          schema:
            type: string
      responses:
        "200":
          description: 'Success'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DropshipDealResult'
        "500":
          description: 'Some internal error'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResult'
    put:
      tags:
        - DropshipDeals
      summary: Update Dropship Deal by id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DropshipDealResult'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResult'
        '500':
          description: Internal error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResult'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DropshipDealPutRequest'
components:
  schemas:
  # Common
    ErrorResult:
      type: object
      properties:
        messages:
          type: array
          items:
            $ref: "#/components/schemas/Message"
      description: "Message field is not required"
    Message:
      type: object
      properties:
        level:
          type: string
          enum:
            - emergency
            - alert
            - critical
            - error
            - warning
            - notice
            - info
        type:
          type: string
          enum:
            - UNDEFINED
            - LOGGER_MESSAGE
          description: >
            You can expose this enum for all your errors
            UNDEFINED - Any undefined message type
            LOGGER_MESSAGE - Same as undefined
        text:
          type: string
          description: Message, that describes what went wrong
    SuccessResult:
      allOf:
        - $ref: '#/components/schemas/ErrorResult'
      type: object
      properties:
        data:
          type: object

    # Dropship Deals
    DropshipDealResult:
      allOf:
        - $ref: '#/components/schemas/SuccessResult'
      type: object
      properties:
        data:
          $ref: '#/components/schemas/DropshipDeal'

    DropshipDealListResult:
      allOf:
        - $ref: '#/components/schemas/SuccessResult'
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/DropshipDeal'

    DropshipDealPostRequest:
      type: object
      properties: {}

    DropshipDealPutRequest:
      type: object
      properties: {}

    DropshipProduct:
      type: object
      description: >
        Object, represents item in bag. Each object does
        not include quantity. If item there are 2 items in deal,
        it will be duplicated.
      properties:
        id: 
          type: string
          description: Id of item in CRM (rollunId)
          example: XDE4R
        price:
          type: number
          description: unit price
          example: 42
        title:
          type: string
          description: The title of the items
          example: 'CRG 1001500112'
  
    Customer:
      type: object
      required: 
        - id
        - address
        - contactInfo
        - firstName
        - createdAt
        - updatedAt
      properties:
        id:
          type: string
          description: Unique identificator of order deal (generated by server).
          example: "AP7734"
        firstName:
          type: string
          description: The first name of the customer
        lastName:
          type: string
          description: The last name of the customer
        address:
          type: object
          required: 
            - city
            - street1
            - street2
            - zip
            - state
          properties:
            city:
              type: string
            street1:
              type: string
            street2:
              type: string
            zip:
              type: string
            state:
              type: string
        contactInfo:
          type: object
          required: 
            - phoneNumber
            - email
          properties:
            email:
              type: string
            phoneNumber:
              type: string
        createdAt:
          type: string
          description: When entity was created
          format: 'date-time'
        updatedAt:
          type: string
          description: When entity was created
          format: 'date-time'


    DropshipDeal:
      type: object
      required: 
        - id
        - createdAt
        - orderDealId
        - updatedAt
      properties:
        id:
          type: string
          description: Unique identificator of Dropship deal (generated by server).
          example: "AP7734"
        orderDealId:
          type: string
          description: A reference to parent Order Deal
        products:
          type: array
          items:
            $ref: '#/components/schemas/DropshipProduct'
        customer:
          $ref: '#/components/schemas/Customer'
        marketplace:
          type: object
          properties:
            name:
              type: string
              description: The name of marketplace where order originated from
              example: Amazon Shoptimistic
            orderNumber:
              type: string
              description: The order number for original order on marketplace
              example: '111333-133-3322'
            tracknumberAddedAt:
              type: string
              format: date-time
              description: The date when tn was added to marketplace
        supplier:
          type: object
          properties:
            name:
              type: object
              description: The name of the supplier
              example: PartsUnlimited
            shippingMethod:
              type: string
              description: Shipping method, that supplier used to send order.
              example: Standard
            orderNumber:
              type: string
              description: Order number from supplier
              example: A8XC3
            paymentCard:
              type: string
              description: The card, that was used to pay for order from supplier
              example: op acct
            virtualName: 
              type: string
            orderId: 
              type: string
              description: The order id from supplier
              example: PartsUnlimited | A8XC3
            orderStatus:
              type: string
              description: Status if the order from supplier
        payment:
          type: object
          properties:
            itemsTotal:
              type: number
              example: 42
        shipping:
          type: object
          properties:
            tracknumber:
              type: string
            carrier:
              type: string
            labelsCreatedAt:
              type: string
              format: date-time
            status:
              type: string
            sender:
              type: string
              example: pu_ds_b
        problem:
          type: string
          description: The problem with order, null if everything is fine
          example: Something went wrong
        createdAt:
          type: string
          description: When entity was created
          format: 'date-time'
        updatedAt:
          type: string
          description: When entity was created
          format: 'date-time'