openapi: 3.0.0
info:
  version: "1"
  title: "EasyPost test"
  description: Long running tasks interface
servers:
  - url: http://hostname
tags: 
  - name: TrackingNumber
paths:
  "/track/{id}":
    get:
      tags:
        - Track
      summary: Get status of track
      description: "Return status of track by tracknumber and carrier"
      parameters:
        - in: path
          name: id
          description: Composite id tracknumber:carrier
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Status of track
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TrackResponse'
        "204":
          description: Incorrect id
        "500":
          description: Error fetching task
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        messages: 
          type: array
          items:
            $ref: "#/components/schemas/Message"
      description: "message field is not required"
    Message:
      type: object
      properties:
        level:
          type: string
          enum:
            - info
            - warning
            - error
        text:
          type: string
          description: Message, that describes what went wrong
    Response:
      allOf:
        - $ref: '#/components/schemas/ErrorResponse'
      type: object
      properties:
        data:
          type: object
    TrackResponse:
      allOf:
        - $ref: '#/components/schemas/Response'
      type: object
      properties:
        data:
          $ref: '#/components/schemas/Track'
    Track:
      type: object
      properties:
        status:
          type: string
          description: Track status
          example: 'pre_transit'
  
