openapi: 3.0.0
info:
  version: "1"
  title: "EditCompatibles"
  description: Edit compatibles
servers:
  - url: http://catalog/openapi/EditCompatibles/v1
tags:
  - name: Compatibles
paths:
  "/multiUpdateOrCreate/{supplierName}":
    put:
      tags:
        - Compatibles
      summary: "Update multiple records, and if some not exist - create them"
      parameters:
        - in: path
          name: "supplierName"
          description: "Supplier name (same as id from https://rollun.net/suppliers)"
          required: true
          schema:
            type: string
            enum:
              - PartsUnlimited
              - RockyMountain
              - TuckerRocky
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateOrCreateRequest'
      responses:
        "201":
          description: "Updated"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UpdateOrCreateResult"
        "500":
          description: "Internal error"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResult'

components:
  schemas:
    ErrorResult:
      type: object
      properties:
        messages:
          type: array
          items:
            $ref: "#/components/schemas/Message"
      description: "Message field is not required"
    Message:
      type: object
      properties:
        level:
          type: string
          enum:
            - emergency
            - alert
            - critical
            - error
            - warning
            - notice
            - info
        type:
          type: string
          enum:
            - UNDEFINED
            - INVALID_RESPONSE
          description: >
            UNDEFINED - Any undefined message type
            INVALID_RESPONSE - A message generated by the client stating that the response could not be decoded
        text:
          type: string
          description: Message, that describes what went wrong
    SuccessResult:
      allOf:
        - $ref: '#/components/schemas/ErrorResult'
      type: object
      properties:
        data:
          type: object
    UpdateOrCreateRequest:
      type: object
      required:
        - compatibles
      properties:
        compatibles:
          type: array
          items:
            $ref: '#/components/schemas/CompatibleInput'
    UpdateOrCreateResult:
      allOf:
        - $ref: '#/components/schemas/SuccessResult'
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/CompatibleOutput'


    ## Resource object
    Compatible:
      type: object
      properties:
        id:
          type: string
          description: Compatible composed id
          example: '934fb3ae1ac0de141fea96ead2d5fa28'
        make:
          type: string
        model:
          type: string
        year:
          type: integer
          format: 'yyyy'

    CompatibleInput:
      type: object
      allOf:
        - $ref: '#/components/schemas/Compatible'
      required:
        - make
        - model
        - year

    CompatibleOutput:
      type: object
      allOf:
        - $ref: '#/components/schemas/Compatible'
      required:
        - id
