openapi: 3.0.0
info:
  version: "1"
  title: "Skeleton"
  description: Manifest description
servers:
  - url: http://server-host/openapi/Skeleton/v1
tags:
  - name: Resource
paths:
  "/resource":
    post:
      tags:
        - Resource
      summary: "Make an resource"
      description: ""
      requestBody:
        description: ""
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderPostRequest'
      responses:
        "200":
          description: "Order successfully created"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderResult'
        "500":
          description: 'Some internal error'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    RollunRequest:
      type: object
      properties:
        payload:
          nullable: true
    RollunResponse:
      type: object
      required:
        - data
      properties:
        metadata:
          type: object
        data:
          nullable: true
        warnings:
          type: array
          items:
            $ref: "#/components/schemas/Warning"
    Error:
      type: object
      required:
        - problem
      properties:
        problem:
          $ref: "#/components/schemas/Problem"
        warnings:
          type: array
          items:
            $ref: "#/components/schemas/Warning"
    Warning:
      type: object
      required:
        - type
        - title
        - detail
      properties:
        type:
          type: string
          format: uri
        title:
          type: string
        detail:
          type: string
    Problem:
      description: A Problem Details object (RFC 7807)
      type: object
      required:
        - type
        - title
        - status
        - detail
        - instance
      properties:
        type:
          type: string
          format: uri
        title:
          type: string
          example: Service Unavailable
        status:
          type: integer
          format: int32
          description: HTTP status code
          minimum: 400
          maximum: 600
          exclusiveMaximum: true
          example: 503
        detail:
          type: string
        instance:
          type: string
          format: uri
          description: Lifecycle token

    ## One resource result
    OrderResult:
      allOf:
        - $ref: '#/components/schemas/RollunResponse'
      type: object
      properties:
        data:
          $ref: '#/components/schemas/Order'


    ## Body for post request
    OrderPostRequest:
      type: object
      allOf:
        - $ref: '#/components/schemas/RollunRequest'

    ## Resource object
    Order:
      type: object
      properties:
        id:
          type: string
          description: Unique identificator of order (generated by server).
          example: "AP7734"