openapi: 3.0.0
info:
  version: "1"
  title: "SupplierItemIdsMapper"
  description: Manifest description
servers:
  - url: http://suppliers/openapi/SupplierItemIdsMapper/v1
tags:
  - name: CsnWithRid
paths:
  "/csnWithRid":
    get:
      tags:
        - CsnWithRid
      summary: "Get list of resource"
      description: "Get list of resource. If no matches are found csn <-> rid, an empty array with no errors will be returned."
      parameters:
        - in: query
          name: "supplierName"
          description: "Supplier name (same as id from https://rollun.net/suppliers)"
          required: true
          example: "Autodist"
          schema:
            type: string
        - in: query
          name: "date"
          description: "The date on which the compliance should be returned. (Sometimes matches change and one csn starts to match another)"
          required: false
          example: "2020-07-21T17:32:28Z"
          schema:
            type: string
            format: date-time
        - in: query
          name: "csn"
          description: "Find rid by csn."
          required: false
          schema:
            type: string
        - in: query
          name: "rid"
          description: "Find csn by rid."
          required: false
          schema:
            type: string
        - in: query
          name: "rids"
          description: "Array of rollunId with date."
          required: false
          schema:
            type: array
            items:
              $ref: "#/components/schemas/RidWithDate"
        - in: query
          name: "csns"
          description: "Array of csn with date."
          required: false
          schema:
            type: array
            items:
              $ref: "#/components/schemas/CsnWithDate"
      responses:
        "200":
          description: "Success"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CsnWithRidListResult"
        '500':
          description: "Internal error"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResult'
components:
  schemas:
    ErrorResult:
      type: object
      properties:
        messages:
          type: array
          items:
            $ref: "#/components/schemas/Message"
      description: "Message field is not required"
    Message:
      type: object
      properties:
        level:
          type: string
          enum:
            - emergency
            - alert
            - critical
            - error
            - warning
            - notice
            - info
        type:
          type: string
          enum:
            - UNDEFINED
            - INVALID_RESPONSE
            - CSN_BY_RID_NOT_FOUND
            - RID_BY_CSN_NOT_FOUND
          description: >
            UNDEFINED - Any undefined message type
            INVALID_RESPONSE - A message generated by the client stating that the response could not be decoded
        text:
          type: string
          description: Message, that describes what went wrong
    SuccessResult:
      allOf:
        - $ref: '#/components/schemas/ErrorResult'
      type: object
      properties:
        data:
          type: object

    CsnWithRidListResult:
      allOf:
        - $ref: '#/components/schemas/SuccessResult'
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/CsnWithRid'
            
    # Query components
    CsnWithDate:
      type: object
      properties:
        csn:
          type: string
        date:
          type: string
          format: date-time
          description: "The date on which the compliance should be returned. (Sometimes matches change and one csn starts to match another rid)"
    RidWithDate:
      type: object
      properties:
        rid:
          type: string
        date:
          type: string
          format: date-time
          description: "The date on which the compliance should be returned. (Sometimes matches change and one rid starts to match another csn)"

    ## Resource object
    CsnWithRid:
      type: object
      properties:
        rid:
          type: string
          description: Rollun id
          example: "RID01"
        csn:
          type: string
          description: Csn
          example: 'CSN01'
        supplierName:
          type: string
          description: Supplier name (same as id from https://rollun.net/suppliers)
          example: 'Autodist'